services:
  accounts:
    image: accounts
    container_name: accounts
    build: .
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - banking-service
  loans:
    image: loans
    container_name: loans
    build: .
    ports:
      - 8090:8090
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - banking-service
  cards:
    image: cards
    container_name: cards
    build: .
    ports:
      - 9000:9000
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - banking-service
networks:
  banking-service:
    driver: bridge